import {CITIES,TOURIST_POINTS,DEMO_HOTELS} from "./data.js";
const app=document.getElementById("app"),toast=document.getElementById("toast"),alfred=document.getElementById("alfred");
let globe=null,map=null,hoverTimer=null,selectedCity=localStorage.getItem("atlasCity")||"Tokyo",activeTab="overview",hotelTier="all";
const bookingAid=localStorage.getItem("bookingAid")||"YOUR_BOOKING_AID";
function route(r){location.hash=r} function current(){return location.hash.slice(1)||"entry"}
function showToast(m){toast.textContent=m;toast.classList.add("on");clearTimeout(window._t);window._t=setTimeout(()=>toast.classList.remove("on"),2000)}
function nav(mode){return `<div class="top"><div class="shell"><header class="nav"><div class="brand"><i></i>${mode}</div><div class="navlinks">${mode==="MONDO"?`<button data-route="mondo">Accueil</button><button data-route="explore">Explorer</button><button data-route="trip">Voyages</button><button data-route="navigator">Créer / Naviguer</button><button data-route="community">Communauté</button><button data-route="mondoblog">Blog</button>`:`<button data-route="atlas">Accueil</button><button data-route="city">Destinations</button><button data-route="stays">Hôtels</button><button data-route="flights">Vols</button><button data-route="city">Activités</button><button data-route="atlasblog">Guides</button>`}</div><div class="navright"><button class="switch" data-route="${mode==="MONDO"?"atlas":"mondo"}">${mode==="MONDO"?"Atlas ↗":"Mondo ↗"}</button><button class="avatar">NA</button></div></header></div></div>`}
function footer(){return `<footer class="footer shell"><div class="footer-grid"><div><div class="brand"><i></i>MONDO × ATLAS</div><h2>Un seul onglet pour préparer le monde.</h2></div><div><h4>Mondo</h4><a data-route="explore">Explorer</a><a data-route="community">Communauté</a><a data-route="mondoblog">Journal</a></div><div><h4>Atlas</h4><a data-route="city">City OS</a><a data-route="stays">Hôtels</a><a data-route="flights">Vols</a></div><div><h4>Ressources</h4><a data-route="city">Visa</a><a data-route="city">Météo</a><a data-route="atlasblog">Guides</a></div></div></footer>`}
function fab(){return `<button class="alfred-fab" data-alfred>A</button>`}
function entry(){return `<main class="entry"><button class="entry-side left" data-route="mondo" aria-label="Mondo"></button><button class="entry-side right" data-route="atlas" aria-label="Atlas"></button><div class="entry-bg"></div><div class="entry-hint">Mondo pour rencontrer · Atlas pour organiser</div></main>`}
function mondo(){return `<main>${nav("MONDO")}<section class="hero mondo-hero"><div class="hero-bg" data-parallax></div><div class="shell hero-content"><div class="eyebrow" style="color:#fff">MONDO · rencontres & aventures</div><h1>Des inconnus.<br>Une route.<br>Une histoire.</h1><p>Backpacks sur le dos, ciel bleu devant vous. Trouvez les personnes qui veulent vivre la même aventure, puis construisez-la ensemble.</p><div class="hero-actions"><button class="btn white" data-route="explore">Trouver ma tribu →</button><button class="btn primary" data-route="navigator">Tracer une aventure</button><button class="btn ghost" data-route="mondoblog">Lire les histoires</button></div></div><div class="floatcard f1"><span class="pulse"></span><div class="eyebrow">Robin live</div><h3>12 groupes correspondent aujourd’hui</h3><p>Japon · Bali · Pérou · Maroc</p></div><div class="floatcard f2"><div class="eyebrow">Le prochain départ</div><h3>Thaïlande · J−45</h3><p>8/10 places · budget 1 250 €</p></div></section>
<section class="section shell reveal"><div class="sectionhead"><div><div class="eyebrow">À rejoindre maintenant</div><h2>Le voyage est plus vendeur quand on voit l’histoire qui commence.</h2></div><p>Chaque carte mène quelque part : groupe, participants, budget, trajet, décisions et discussion.</p></div><div class="grid3">${photoCard("Japon · 14 jours","Tokyo → Kyoto → Osaka","96% match · 2 places","https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1600&q=92","trip")}${photoCard("Bali · novembre","Ubud → Canggu → Lombok","Groupe en formation","https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1300&q=92","trip")}${photoCard("Pérou · décembre","Lima → Cusco → Machu Picchu","86% match","https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=1300&q=92","trip")}</div></section>
<section class="world-section reveal"><div class="world-copy"><div class="eyebrow">Mondo World Explorer</div><h2>Maintenez la souris sur un pays.</h2><p>Le pays se soulève, le globe se rapproche et les villes touristiques apparaissent. Cliquez sur une ville pour voir les voyages Mondo correspondants.</p><button class="btn" data-route="explore">Plein écran →</button></div><div class="globe-wrap"><div id="worldGlobe"></div><div class="country-panel" id="countryPanel"><div class="eyebrow">Explorer</div><h3>Survolez un pays</h3><p>Ses contours seront mis en évidence et ses destinations apparaîtront.</p><div class="tourist-cities"></div></div><div class="world-hint">Maintenir 0,7 s · zoom automatique · cliquer pour verrouiller</div></div></section>
<section class="section shell reveal"><div class="sectionhead"><div><div class="eyebrow">Mondo Journal</div><h2>Les meilleures informations viennent aussi de ceux qui viennent de rentrer.</h2></div><p>Récits, budgets réels, erreurs, conseils de groupe et itinéraires vécus.</p></div>${storyCards()}</section>${footer()}${fab()}</main>`}
function photoCard(t,s,b,img,r){return `<article class="card photo-card" data-route="${r}"><img src="${img}"><div class="cardtext"><span class="chip">${b}</span><h3>${t}</h3><p>${s}</p></div></article>`}
function storyCards(){return `<div class="story-grid">${photoCard("15 jours au Japon à 1 780 €","Le budget réel de notre groupe de 4","Budget réel","https://images.unsplash.com/photo-1492571350019-22de08371fd3?auto=format&fit=crop&w=1200&q=90","trip")}${photoCard("Partir avec des inconnus","7 règles qui ont sauvé notre roadtrip","Communauté","https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=90","mondoblog")}${photoCard("Bali autrement","Ce qu’on referait — et ce qu’on éviterait","Retour d’expérience","https://images.unsplash.com/photo-1533669955142-6a73332af4db?auto=format&fit=crop&w=1200&q=90","mondoblog")}</div>`}
function explore(){return `<main>${nav("MONDO")}<section class="world-section" style="min-height:100vh"><div class="world-copy" style="top:110px"><div class="eyebrow">Explorer le monde</div><h2>Voyages en temps réel.</h2><p>Survolez, zoomez, verrouillez un pays, puis choisissez une ville.</p></div><div class="globe-wrap" style="width:82%"><div id="worldGlobe"></div><div class="country-panel" id="countryPanel"><h3>Choisissez un pays</h3><div class="tourist-cities"></div></div></div></section>${fab()}</main>`}
function atlas(){return `<main class="atlas-dash">${nav("ATLAS")}<section class="hero atlas-hero"><div class="hero-bg" data-parallax></div><div class="shell hero-content" style="padding-bottom:180px"><div class="eyebrow" style="color:#fff">ATLAS · votre Travel OS</div><h1>Un seul endroit.<br>Tout votre voyage.</h1><p>Visa, météo, quartiers, hôtels, vols, food, transports, activités et guides. Finies les quinze pages ouvertes pour comprendre une destination.</p></div><div class="searchbar"><div class="searchcell"><small>Destination</small><b>${selectedCity}</b></div><div class="searchcell"><small>Dates</small><b>10–24 octobre</b></div><div class="searchcell"><small>Voyageurs</small><b>4 personnes</b></div><div class="searchcell"><small>Budget</small><b>2 000 € / pers.</b></div><button class="btn primary" data-route="city">Ouvrir le Travel OS →</button></div></section>
<section class="section shell reveal"><div class="sectionhead"><div><div class="eyebrow">Tout est relié</div><h2>Une ville n’est pas une liste d’hôtels.</h2></div><p>Atlas relie quartier, activités, nourriture, temps de transport et budget pour que votre logement soit au bon endroit pour votre voyage.</p></div><div class="atlas-tools">${tool("🗺","Quartiers","city","nightlife, famille, culture")}${tool("🏨","Hôtels","stays","50 candidats / ville")}${tool("✈","Vols","flights","prix + fatigue + bagages")}${tool("☀","Météo","city","quand partir, quoi porter")}${tool("🍜","Food","city","quoi manger, où")}${tool("🛂","Visa","city","selon votre passeport")}</div></section>
<section class="section shell reveal"><div class="sectionhead"><div><div class="eyebrow">20 hubs déjà structurés</div><h2>Asie, Europe, Amériques, Afrique.</h2></div><p>Choisissez une ville : Atlas charge son profil quartiers, son catalogue hôtel et son hub de préparation.</p></div><div class="knowledge-grid">${Object.entries(CITIES).slice(0,12).map(([n,m])=>`<article class="article" data-city="${n}"><div><div class="eyebrow">${m.continent}</div><h3>${n}</h3><p>${m.neighborhoods.slice(0,3).map(x=>x.name).join(" · ")}</p></div><button class="btn">Ouvrir →</button></article>`).join("")}</div></section>${footer()}${fab()}</main>`}
function tool(i,n,r,s){return `<button class="tool" data-route="${r}"><span>${i}</span><b>${n}</b><small>${s}</small></button>`}
function city(){const c=CITIES[selectedCity];return `<main class="city-os">${nav("ATLAS")}<div class="shell"><header class="city-header"><div><div class="eyebrow">${c.continent} · ${c.country}</div><h1>${selectedCity}, votre tableau de bord.</h1><p>Tout ce qu’il faut pour préparer la ville sans quitter Atlas.</p></div><select id="citySelect" class="city-select">${Object.keys(CITIES).map(n=>`<option ${n===selectedCity?"selected":""}>${n}</option>`).join("")}</select></header><nav class="hub-tabs">${["overview","neighborhoods","hotels","visa","weather","activities","food","transport","guides"].map(t=>`<button class="chip ${activeTab===t?"on":""}" data-tab="${t}">${tabLabel(t)}</button>`).join("")}</nav><div id="tabContent">${cityTab(c)}</div></div>${footer()}${fab()}</main>`}
function tabLabel(t){return {overview:"Vue d’ensemble",neighborhoods:"Quartiers",hotels:"Hôtels",visa:"Visa",weather:"Météo",activities:"Activités",food:"Food",transport:"Transports",guides:"Guides"}[t]}
function cityTab(c){
 if(activeTab==="overview"||activeTab==="neighborhoods") return `<div class="city-layout"><div class="mapbox"><div id="atlasMap" style="height:100%"></div><div class="map-overlay"><b>${selectedCity} · Atlas Map</b><small>3D · quartiers · hôtels · activités · food</small></div></div><aside class="sidebar"><section class="side"><div class="eyebrow">Quel quartier vous correspond ?</div><h3>Choisissez selon votre voyage.</h3><div class="neigh-list">${c.neighborhoods.map((n,i)=>neighCard(n,i===0)).join("")}</div></section><section class="side"><div class="eyebrow">Infos pratiques</div><h3>${c.currency} · ${c.timezone}</h3><p>Meilleure période : ${c.best}</p><button class="btn" data-tab-click="visa">Visa / entrée</button> <button class="btn" data-tab-click="weather">Météo</button></section></aside></div>`;
 if(activeTab==="hotels") return hotelCatalog();
 if(activeTab==="visa") return infoPanel("Visa & entrée","Le moteur final utilise nationalité, type de passeport, destination, durée et motif. Les règles sont récupérées depuis des sources officielles et datées.","🛂","La donnée ne doit jamais être codée en dur. Avant départ, Atlas revérifie automatiquement.");
 if(activeTab==="weather") return infoPanel("Météo & saison","Climat du séjour, température, pluie, humidité, coucher du soleil, meilleure période et conseils vêtements.","☀",`Période recommandée pour ${selectedCity} : ${c.best}. La production branchera une API météo temps réel.`);
 if(activeTab==="activities") return listPanel("Activités phares",["Les incontournables","Une activité locale","Une journée hors des sentiers battus","Observation / panorama","Expérience culturelle","Option pluie"],"🎟");
 if(activeTab==="food") return listPanel("Food guide",["Les plats à absolument goûter","Street food / petits budgets","Restaurants milieu de gamme","Expérience premium","Petit-déjeuner local","Marché ou food hall"],"🍜");
 if(activeTab==="transport") return listPanel("Se déplacer",["Depuis l’aéroport","Transport public","Taxi / VTC","Carte ou pass transport","Dernier métro / horaires","Pièges à éviter"],"🚇");
 return `<section class="section" style="padding-top:25px"><div class="sectionhead"><div><div class="eyebrow">Atlas Guides</div><h2>Le blog fait partie du voyage.</h2></div><p>Les articles répondent aux questions que vous auriez autrement cherchées dans de nouveaux onglets.</p></div>${atlasArticles(c)}</section>`;
}
function neighCard(n,a){return `<button class="neigh ${a?"active":""}" data-neigh="${n.name}"><div class="neigh-head"><b>${n.name}</b><strong>${n.score}%</strong></div><small>${n.desc}</small><div class="tags">${n.tags.map(t=>`<span class="tag">${t}</span>`).join("")}</div></button>`}
function infoPanel(t,d,icon,detail){return `<section class="section" style="padding-top:25px"><div class="panel"><div style="font-size:50px">${icon}</div><div class="eyebrow">Atlas Practical</div><h2>${t}</h2><p class="muted">${d}</p><div class="affiliate-note">${detail}</div><button class="btn primary" data-toast="Cette source sera reliée au moteur de production">Voir la source officielle →</button></div></section>`}
function listPanel(t,items,icon){return `<section class="section" style="padding-top:25px"><div class="sectionhead"><div><div class="eyebrow">Atlas Curated</div><h2>${icon} ${t}</h2></div><p>Une petite sélection organisée plutôt qu’une liste infinie.</p></div><div class="knowledge-grid">${items.map((x,i)=>`<article class="article" data-toast="${x} ajouté au voyage"><div><div class="eyebrow">#${i+1}</div><h3>${x}</h3><p>Carte, distance depuis votre hôtel, horaires, coût et conseil Alfred seront reliés ici.</p></div><button class="btn">Ajouter →</button></article>`).join("")}</div></section>`}
function atlasArticles(c){return `<div class="knowledge-grid">${["Quel quartier choisir selon votre profil ?","Premier voyage : ce qu’il faut savoir","Manger comme un local sans perdre une journée","Les erreurs qui coûtent du temps","48 heures parfaites","Budget réel : cheap, confort ou premium ?"].map((x,i)=>`<article class="article"><div><div class="eyebrow">${selectedCity} · guide ${i+1}</div><h3>${x}</h3><p>${c.neighborhoods[i%c.neighborhoods.length].desc}</p></div><button class="btn" data-toast="Article ouvert dans le hub, sans nouvel onglet">Lire →</button></article>`).join("")}</div>`}
function hotelCatalog(){let list=DEMO_HOTELS[selectedCity];if(hotelTier!=="all")list=list.filter(h=>h.tier===hotelTier);return `<section class="section" style="padding-top:25px"><div class="catalog-head"><div><div class="eyebrow">50 candidats · ${selectedCity}</div><h2>Le catalogue avant la sélection Atlas.</h2></div><div class="hotel-filters">${["all","cheap","mid","premium"].map(t=>`<button class="chip ${hotelTier===t?"on":""}" data-tier="${t}">${t==="all"?"Tous":t==="cheap"?"€ Prix minimum":t==="mid"?"€€ Confort":"€€€ Premium"}</button>`).join("")}</div></div><div class="affiliate-note">Cette archive contient 50 emplacements de catalogue par ville. Quand vos identifiants Booking.com Demand API seront ajoutés sur l’hébergement, Atlas pourra remplacer ces candidats démo par l’inventaire réel, puis appliquer votre sélection éditoriale. Le programme officiel Booking.com permet la recherche puis la redirection affiliée.</div><div class="hotel-grid">${list.map(h=>hotelCard(h)).join("")}</div></section>`}
function hotelCard(h){const url=`https://www.booking.com/searchresults.html?ss=${encodeURIComponent(selectedCity)}${bookingAid!=="YOUR_BOOKING_AID"?`&aid=${bookingAid}`:""}`;return `<article class="hotel"><div class="hotel-top"></div><div class="hotel-body"><span class="tag">${h.tier}</span><h3>${h.name}</h3><p>${h.neighborhood} · candidat catalogue non audité</p><div class="hotel-meta"><span>Score pré-filtre ${h.score}</span><span class="hotel-price">≈ ${h.price} €</span></div><button class="btn" data-external="${url}">Voir disponibilité →</button></div></article>`}
function stays(){activeTab="hotels";return city()}
function flights(){const fs=[["Option équilibre","1 escale courte","612 €"],["Direct","Confort prioritaire","742 €"],["Prix minimum","1 escale","548 €"]];return `<main class="city-os">${nav("ATLAS")}<div class="shell"><header class="city-header"><div><div class="eyebrow">Atlas Flights</div><h1>Le vol doit servir le voyage.</h1><p>Prix, horaires, bagages, fatigue et aéroport d’arrivée sont évalués ensemble.</p></div></header><div class="knowledge-grid">${fs.map((f,i)=>`<article class="article"><div><div class="eyebrow">${f[1]}</div><h3>${f[0]}</h3><p>Paris → ${selectedCity} · bagage cabine + soute</p></div><strong style="font-size:24px">${f[2]}</strong><button class="btn" data-toast="Option ajoutée au voyage">Choisir →</button></article>`).join("")}</div></div>${footer()}${fab()}</main>`}
function trip(){return `<main class="city-os">${nav("MONDO")}<div class="shell"><header class="city-header"><div><div class="eyebrow">JP-1048 · voyage partagé</div><h1>Japon, 14 jours, 4 voyageurs.</h1><p>Tout ce qui est décidé ici est disponible dans Atlas.</p></div></header><div class="workspace"><section class="panel"><div class="eyebrow">84% prêt</div><h2>Tokyo → Kyoto → Osaka</h2><div class="facts"><div class="fact"><small>Dates</small><b>10–24 oct.</b></div><div class="fact"><small>Budget</small><b>2 000 €</b></div><div class="fact"><small>Participants</small><b>4 / 4</b></div><div class="fact"><small>Départ</small><b>Paris</b></div></div><div class="route">${["Tokyo · 5 nuits","Kyoto · 4 nuits","Osaka · 5 nuits"].map((x,i)=>`<div class="route-row"><b>0${i+1}</b><span>${x}</span><b>✓</b></div>`).join("")}</div></section><aside class="panel butler"><div class="aicon">A</div><div class="eyebrow">Alfred</div><h2>Votre voyage est réservable.</h2><p class="muted">Atlas connaît déjà les dates, le groupe, l’itinéraire et le budget.</p><button class="btn lime" data-route="city">Ouvrir dans Atlas →</button></aside></div></div>${footer()}${fab()}</main>`}
function mondoblog(){return `<main>${nav("MONDO")}<div class="shell"><section class="bloghero"><div class="eyebrow">Mondo Journal</div><h1>Les histoires qui donnent envie de partir.</h1><p>Guides communautaires, budgets réels, rencontres, erreurs et récits de groupes.</p></section>${storyCards()}<section class="section"><div class="knowledge-grid">${["Comment choisir des compagnons de voyage ?","Budget réel d’un backpacking en Asie","Que faire quand le groupe n’est pas d’accord ?","Les meilleurs sacs pour 3 semaines","Dormir en auberge quand on voyage à plusieurs","Créer un itinéraire sans tuer la spontanéité"].map(x=>`<article class="article"><h3>${x}</h3><p>Article intégré à Mondo. Les informations utiles peuvent être ajoutées directement au voyage.</p><button class="btn" data-toast="Article ouvert">Lire →</button></article>`).join("")}</div></section></div>${footer()}${fab()}</main>`}
function community(){return mondoblog()}
function atlasblog(){activeTab="guides";return city()}

const ALBANIA_POIS=[
 {name:"Tirana",lat:41.3275,lng:19.8187,days:"1–2 jours",type:"ville",summary:"Point de départ idéal : cafés, musées, Blloku et logistique facile.",highlights:["Blloku","marchés","culture urbaine"]},
 {name:"Shkodër",lat:42.0693,lng:19.5033,days:"1–2 jours",type:"ville",summary:"Porte des Alpes albanaises, lac de Shkodër et château de Rozafa.",highlights:["lac","vélo","Alpes"]},
 {name:"Theth",lat:42.3953,lng:19.7747,days:"2–3 jours",type:"montagne",summary:"Village alpin isolé : randonnées, vallée spectaculaire et aventure.",highlights:["randonnée","Alpes","nature"]},
 {name:"Berat",lat:40.7058,lng:19.9522,days:"1–2 jours",type:"culture",summary:"Ville historique, quartiers ottomans et vues depuis la citadelle.",highlights:["UNESCO","architecture","food"]},
 {name:"Vlorë",lat:40.4661,lng:19.4914,days:"2–3 jours",type:"mer",summary:"Porte de la Riviera : Lungomare, baie, Narta et route côtière vers le sud.",highlights:["mer","Lungomare","Riviera"]},
 {name:"Himarë",lat:40.1017,lng:19.7447,days:"2–4 jours",type:"plage",summary:"Base détendue sur la Riviera, plages, criques et accès à Porto Palermo.",highlights:["plages","criques","roadtrip"]},
 {name:"Gjirokastër",lat:40.0758,lng:20.1389,days:"1–2 jours",type:"culture",summary:"Vieille ville de pierre, château et excellente étape culturelle dans le sud.",highlights:["UNESCO","château","gastronomie"]},
 {name:"Sarandë",lat:39.8756,lng:20.0053,days:"2–3 jours",type:"mer",summary:"Base côtière pour Butrint, Ksamil et les paysages du sud.",highlights:["Butrint","Ksamil","mer"]},
 {name:"Korçë",lat:40.6186,lng:20.7808,days:"1–2 jours",type:"ville",summary:"Sud-est culturel, gastronomie, architecture et rythme plus local.",highlights:["culture","food","local"]},
 {name:"Përmet",lat:40.2336,lng:20.3517,days:"1–2 jours",type:"nature",summary:"Vallée de la Vjosa, nature, cuisine locale et accès aux bains thermaux.",highlights:["Vjosa","nature","thermes"]}
];
let navigatorState={
 role:"organizer",
 stops:[
  {id:"s1",name:"Tirana",lat:41.3275,lng:19.8187,days:2},
  {id:"s2",name:"Berat",lat:40.7058,lng:19.9522,days:2},
  {id:"s3",name:"Vlorë",lat:40.4661,lng:19.4914,days:3}
 ],
 proposals:[
  {id:"p1",author:"Sarah",type:"add",name:"Himarë",lat:40.1017,lng:19.7447,message:"On pourrait ajouter Himarë entre Vlorë et Gjirokastër pour 2 nuits plage ?"}
 ],
 requests:[
  {id:"r1",name:"Lina",initials:"LI",message:"Salut ! Je rêve de faire l’Albanie en sac à dos. Je suis flexible sur les dates et j’adore randonnée + food.",status:"pending"}
 ],
 members:["Nassim","Amine","Clara"],
 messages:[
  {from:"Amine",text:"La boucle sud me plaît beaucoup."},
  {from:"Clara",text:"Je vote pour au moins 2 nuits à Himarë."}
 ]
};
let routeMap=null, routeMarkers=[], suggestionPopup=null;

function navigator(){
 return `<main class="navigator">${nav("MONDO")}<div class="shell">
 <header class="navigator-head"><div><div class="eyebrow">MONDO NAVIGATOR · création de voyage</div><h1>Tracez votre aventure.</h1><p>Posez vos étapes comme un navigateur, découvrez ce qui se trouve autour de votre route et laissez le groupe proposer des améliorations sans jamais modifier votre itinéraire sans validation.</p></div>
 <div class="mode-switch"><button class="${navigatorState.role==="organizer"?"on":""}" data-role="organizer">Organisateur</button><button class="${navigatorState.role==="visitor"?"on":""}" data-role="visitor">Futur participant</button></div></header>

 <div class="navigator-layout"><section class="route-map"><div id="routePlannerMap" style="height:100%"></div><div class="route-map-overlay"><div class="route-instruction" id="routeInstruction">${navigatorState.role==="organizer"?"Cliquez n’importe où pour ajouter une étape · faites glisser un point pour l’ajuster · cliquez sur une suggestion pour l’ajouter.":"Explorez le trajet · cliquez sur une suggestion pour proposer un ajustement à l’organisateur."}</div><div class="route-toolbar"><button data-reset-route>↺ Réinitialiser</button><button data-fit-route>⌖ Voir tout</button></div></div></section>

 <aside class="navigator-side">
  <section class="navcard"><div class="eyebrow">Carnet de route</div><h3>Albanie · 14 jours</h3><div class="adventure-status"><div><small>Étapes</small><b id="stopCount">${navigatorState.stops.length}</b></div><div><small>Distance</small><b id="totalDistance">—</b></div><div><small>Voyageurs</small><b>${navigatorState.members.length+1}/6</b></div><div><small>État</small><b>En construction</b></div></div><div class="route-stop-list" id="routeStopList"></div><div class="segment-list" id="segmentList"></div></section>
  ${navigatorState.role==="organizer"?organizerCollab():visitorCollab()}
  <section class="navcard"><div class="eyebrow">Discussion du voyage</div><h3>${navigatorState.members.length+1} aventuriers</h3><div class="chat" id="tripChat">${navigatorState.messages.map(m=>`<div class="bubble ${m.from==="Nassim"?"me":""}"><b>${m.from}</b><br>${m.text}</div>`).join("")}</div><div class="chat-compose"><input id="chatInput" placeholder="Écrire au groupe…"><button data-send-message>↑</button></div></section>
 </aside></div></div>${footer()}${fab()}</main>`;
}
function organizerCollab(){return `<section class="navcard joinbox"><div class="eyebrow">Demandes pour rejoindre</div><h3>Vous gardez le contrôle du groupe.</h3><div id="joinRequests">${navigatorState.requests.filter(r=>r.status==="pending").map(r=>`<div class="join-request" data-request="${r.id}"><b>${r.name}</b><p>${r.message}</p><div class="actions"><button class="btn lime" data-approve-request="${r.id}">Accepter</button><button class="btn" data-reject-request="${r.id}">Refuser</button></div></div>`).join("")||'<p>Aucune demande en attente.</p>'}</div><div class="eyebrow" style="margin-top:12px">Ajustements proposés</div><div id="proposalList">${navigatorState.proposals.map(proposalCard).join("")||'<p>Aucune proposition.</p>'}</div></section>`}
function visitorCollab(){const req=navigatorState.requests.find(r=>r.name==="Vous");return `<section class="navcard joinbox"><div class="eyebrow">Rejoindre l’aventure</div><h3>Présentez-vous avant d’entrer dans le groupe.</h3>${req?`<p>Demande envoyée · statut : <b>${req.status}</b></p>`:`<textarea id="joinMessage" style="width:100%;min-height:90px;background:#071827;border:1px solid #29465f;border-radius:12px;color:#fff;padding:10px" placeholder="Ex : Salut ! J’adore randonnée, food et roadtrips…"></textarea><button class="btn lime" style="margin-top:8px;width:100%" data-request-join>Demander à rejoindre</button>`}<div class="eyebrow" style="margin-top:15px">Proposer un changement</div><p>Sur la carte, cliquez sur une ville suggérée : elle sera envoyée comme proposition. L’organisateur devra l’approuver.</p></section>`}
function proposalCard(p){return `<div class="proposal" data-proposal="${p.id}"><div class="proposal-head"><b>${p.author} propose ${p.name}</b><span class="tag">${p.type}</span></div><p>${p.message}</p><div class="actions"><button class="btn lime" data-approve-proposal="${p.id}">Approuver</button><button class="btn" data-reject-proposal="${p.id}">Refuser</button></div></div>`}

function haversine(a,b){const R=6371,toRad=x=>x*Math.PI/180,dLat=toRad(b.lat-a.lat),dLon=toRad(b.lng-a.lng),la1=toRad(a.lat),la2=toRad(b.lat);const h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h))}
function transportModes(km,a,b){
 const modes=[];
 if(km<8)modes.push(["🚶 Marche","best"]);
 if(km<35)modes.push(["🚲 Vélo",km<20?"best":""]);
 if(km<450)modes.push(["🚗 Voiture","best"],["🚌 Bus",""]);
 if(km>80)modes.push(["👍 Stop",""]);
 if(km>250)modes.push(["✈ Avion",""]);
 return modes;
}
function drawNavigator(){
 const el=document.getElementById("routePlannerMap");if(!el)return;
 routeMap=new maplibregl.Map({container:el,style:"https://tiles.openfreemap.org/styles/liberty",center:[19.86,40.75],zoom:7.1,pitch:48,bearing:-5,antialias:true});
 routeMap.addControl(new maplibregl.NavigationControl({visualizePitch:true}),"bottom-right");
 routeMap.on("load",()=>{
   routeMap.addSource("route",{type:"geojson",data:routeGeo()});
   routeMap.addLayer({id:"route-glow",type:"line",source:"route",paint:{"line-color":"#7652ff","line-width":10,"line-opacity":.18}});
   routeMap.addLayer({id:"route-line",type:"line",source:"route",paint:{"line-color":"#baf34a","line-width":3,"line-dasharray":[2,1]}});
   renderRouteMarkers();renderSuggestionMarkers();updateRouteSidebar();
   routeMap.on("click",e=>{
      if(e.originalEvent.target.closest(".maplibregl-marker"))return;
      if(navigatorState.role!=="organizer"){showToast("En mode participant, ajoutez une ville suggérée pour proposer une modification.");return}
      addFreeStop(e.lngLat.lat,e.lngLat.lng);
   });
 });
}
function routeGeo(){return {type:"Feature",geometry:{type:"LineString",coordinates:navigatorState.stops.map(s=>[s.lng,s.lat])},properties:{}}}
function syncRouteSource(){const src=routeMap?.getSource("route");if(src)src.setData(routeGeo());renderRouteMarkers();updateRouteSidebar()}
function renderRouteMarkers(){
 routeMarkers.forEach(m=>m.remove());routeMarkers=[];
 navigatorState.stops.forEach((s,i)=>{
   const el=document.createElement("button");el.className="stopnum";el.textContent=i+1;el.title=s.name;
   const marker=new maplibregl.Marker({element:el,draggable:navigatorState.role==="organizer"}).setLngLat([s.lng,s.lat]).addTo(routeMap);
   marker.on("dragend",()=>{const p=marker.getLngLat();s.lat=p.lat;s.lng=p.lng;syncRouteSource()});
   marker.getElement().onclick=e=>{e.stopPropagation();showToast(`${s.name} · étape ${i+1}`)};
   routeMarkers.push(marker);
 });
}
function renderSuggestionMarkers(){
 ALBANIA_POIS.filter(p=>!navigatorState.stops.some(s=>s.name===p.name)).forEach(p=>{
   const el=document.createElement("button");el.className="chip";el.textContent="✦ "+p.name;el.style.background="#0d2c3d";el.style.borderColor="#31d7ca";
   const m=new maplibregl.Marker({element:el}).setLngLat([p.lng,p.lat]).addTo(routeMap);
   let timer;
   el.onmouseenter=()=>{timer=setTimeout(()=>showSuggestionCard(p,el),220)};
   el.onmouseleave=()=>{clearTimeout(timer);setTimeout(()=>suggestionPopup?.remove(),150)};
   el.onclick=e=>{e.stopPropagation();navigatorState.role==="organizer"?addSuggestedStop(p):proposeStop(p)};
 });
}
function showSuggestionCard(p,el){
 suggestionPopup?.remove();const node=document.createElement("div");node.className="suggestion-card";node.innerHTML=`<div class="eyebrow">${p.type} · suggestion Mondo</div><h3>${p.name}</h3><strong>Durée idéale : ${p.days}</strong><p>${p.summary}</p><div class="tags">${p.highlights.map(x=>`<span class="tag">${x}</span>`).join("")}</div>`;
 suggestionPopup=node;document.body.appendChild(node);const r=el.getBoundingClientRect();node.style.left=Math.min(innerWidth-280,r.left+20)+"px";node.style.top=Math.max(90,r.top-150)+"px";
 node.onmouseenter=()=>{};node.onmouseleave=()=>node.remove();
}
function addSuggestedStop(p){navigatorState.stops.push({id:"s"+Date.now(),name:p.name,lat:p.lat,lng:p.lng,days:parseInt(p.days)||2});syncRouteSource();showToast(`${p.name} ajouté au trajet`)}
function addFreeStop(lat,lng){const nearest=[...ALBANIA_POIS].sort((a,b)=>haversine({lat,lng},a)-haversine({lat,lng},b))[0];const d=haversine({lat,lng},nearest);navigatorState.stops.push({id:"s"+Date.now(),name:d<18?nearest.name:"Étape libre",lat,lng,days:1});syncRouteSource();showToast("Nouvelle étape ajoutée")}
function proposeStop(p){if(navigatorState.proposals.some(x=>x.name===p.name)){showToast("Cette proposition existe déjà");return}navigatorState.proposals.push({id:"p"+Date.now(),author:"Vous",type:"add",name:p.name,lat:p.lat,lng:p.lng,message:`Je propose d’ajouter ${p.name} (${p.days}) : ${p.summary}`});showToast(`Proposition ${p.name} envoyée à l’organisateur`)}
function removeStop(id){navigatorState.stops=navigatorState.stops.filter(s=>s.id!==id);syncRouteSource()}
function updateRouteSidebar(){
 const list=document.getElementById("routeStopList"),segments=document.getElementById("segmentList");if(!list||!segments)return;
 list.innerHTML=navigatorState.stops.map((s,i)=>`<div class="route-stop"><span class="stopnum">${i+1}</span><div><b>${s.name}</b><br><small>${s.days} jour${s.days>1?"s":""} · glissez le point sur la carte</small></div>${navigatorState.role==="organizer"?`<button class="delete-stop" data-delete-stop="${s.id}">×</button>`:""}</div>`).join("");
 let total=0;const segs=[];for(let i=0;i<navigatorState.stops.length-1;i++){const a=navigatorState.stops[i],b=navigatorState.stops[i+1],km=haversine(a,b);total+=km;const road=Math.round(km*1.22);segs.push(`<div class="segment"><div class="segment-head"><b>${a.name} → ${b.name}</b><strong>≈ ${road} km</strong></div><small>${Math.round(km)} km à vol d’oiseau · estimation route indicative</small><div class="modes">${transportModes(road,a,b).map(([m,c])=>`<span class="mode ${c}">${m}</span>`).join("")}</div></div>`)}
 segments.innerHTML=segs.join("")||"<p>Ajoutez au moins deux étapes.</p>";document.getElementById("totalDistance").textContent=total?`≈ ${Math.round(total*1.22)} km`:"—";document.getElementById("stopCount").textContent=navigatorState.stops.length;
 document.querySelectorAll("[data-delete-stop]").forEach(x=>x.onclick=()=>removeStop(x.dataset.deleteStop));
}

function showAlfred(){alfred.innerHTML=`<button class="close" data-close>×</button><div class="eyebrow">Alfred · Travel OS</div><h2>Je garde les 15 onglets en un seul.</h2><div class="alfred-card">Destination : ${selectedCity}<br>Passeport : français<br>Budget : 2 000 €<br>Voyageurs : 4</div><div class="alfred-card"><b>Je peux maintenant :</b><p>Comparer les quartiers, chercher un hôtel cheap, vérifier le visa, ajouter une activité, résumer la météo ou construire une journée.</p></div><button class="btn primary" data-route="city">Ouvrir le hub ${selectedCity}</button>`;alfred.classList.add("open");alfred.querySelector("[data-close]").onclick=()=>alfred.classList.remove("open");alfred.querySelector("[data-route]").onclick=()=>{alfred.classList.remove("open");route("city")}}
function initGlobe(){
 const host=document.getElementById("worldGlobe");if(!host)return;
 let hoverCountry=null,locked=false;
 globe=Globe()(host).backgroundColor("#050d14").globeImageUrl("https://unpkg.com/three-globe/example/img/earth-blue-marble.jpg").bumpImageUrl("https://unpkg.com/three-globe/example/img/earth-topology.png").showAtmosphere(true).atmosphereColor("#517acb").atmosphereAltitude(.18)
 .pointsData(TOURIST_POINTS).pointLat("lat").pointLng("lng").pointColor(()=>"#baf34a").pointAltitude(.015).pointRadius(.12).pointLabel(d=>`<b>${d.city}</b><br>${d.country}`).onPointClick(d=>{selectedCity=d.city;localStorage.setItem("atlasCity",selectedCity);route("city")});
 fetch("https://cdn.jsdelivr.net/gh/holtzy/D3-graph-gallery@master/DATA/world.geojson").then(r=>r.json()).then(world=>{
   globe.polygonsData(world.features.filter(d=>d.properties.name!=="Antarctica")).polygonCapColor(d=>hoverCountry===d?"rgba(186,243,74,.30)":"rgba(22,53,77,.20)").polygonSideColor(()=>"#26445b").polygonStrokeColor(d=>hoverCountry===d?"#baf34a":"#52728d").polygonAltitude(d=>hoverCountry===d?.045:.007).polygonLabel(d=>`<b>${d.properties.name}</b>`).onPolygonHover(d=>{
      if(locked)return;clearTimeout(hoverTimer);hoverCountry=d;refreshCountry(d);globe.polygonCapColor(globe.polygonCapColor()).polygonAltitude(globe.polygonAltitude());
      if(d)hoverTimer=setTimeout(()=>focusCountry(d),700);
   }).onPolygonClick(d=>{locked=true;hoverCountry=d;refreshCountry(d);focusCountry(d);setTimeout(()=>locked=false,1400)})
 });
 function focusCountry(d){const pts=TOURIST_POINTS.filter(p=>p.country===d.properties.name);if(pts.length){const lat=pts.reduce((a,b)=>a+b.lat,0)/pts.length,lng=pts.reduce((a,b)=>a+b.lng,0)/pts.length;globe.pointOfView({lat,lng,altitude:1.5},900)}}
 function refreshCountry(d){const box=document.getElementById("countryPanel");if(!box||!d)return;const pts=TOURIST_POINTS.filter(p=>p.country===d.properties.name);box.innerHTML=`<div class="eyebrow">Pays sélectionné</div><h3>${d.properties.name}</h3><p>${pts.length?`${pts.length} destination(s) Atlas/Mondo dans cette démo.`:"Maintenez le curseur pour zoomer sur le pays."}</p><div class="tourist-cities">${pts.map(p=>`<span data-city="${p.city}">${p.city}</span>`).join("")}</div>`;box.querySelectorAll("[data-city]").forEach(x=>x.onclick=()=>{selectedCity=x.dataset.city;localStorage.setItem("atlasCity",selectedCity);route("city")})}
 globe.controls().autoRotate=true;globe.controls().autoRotateSpeed=.35;globe.controls().enableDamping=true;
}
function neighborhoodGeo(city){const c=CITIES[city];return {type:"FeatureCollection",features:c.neighborhoods.map((n,i)=>{const d=.011;return {type:"Feature",properties:{name:n.name,score:n.score,color:["#6b4cff","#1d9b73","#d07442","#4384d8","#a44788","#a5853d","#307c8d"][i%7]},geometry:{type:"Polygon",coordinates:[[[n.lon-d,n.lat-d*.7],[n.lon+d,n.lat-d*.6],[n.lon+d*.85,n.lat+d*.8],[n.lon-d*.8,n.lat+d],[n.lon-d,n.lat-d*.7]]]}}})}}
function initMap(){
 const el=document.getElementById("atlasMap");if(!el)return;const c=CITIES[selectedCity];
 map=new maplibregl.Map({container:el,style:"https://tiles.openfreemap.org/styles/liberty",center:[c.lon,c.lat],zoom:selectedCity==="Tokyo"?11.3:11,pitch:48,bearing:-12,antialias:true});
 map.addControl(new maplibregl.NavigationControl({visualizePitch:true}),"bottom-right");
 map.on("load",()=>{
   try{const layers=map.getStyle().layers;const label=layers.find(l=>l.type==="symbol"&&l.layout&&l.layout["text-field"])?.id;if(map.getSource("openmaptiles"))map.addLayer({id:"3d-buildings",source:"openmaptiles","source-layer":"building",type:"fill-extrusion",minzoom:14,paint:{"fill-extrusion-color":"#172c3c","fill-extrusion-height":["coalesce",["get","render_height"],["get","height"],8],"fill-extrusion-base":["coalesce",["get","render_min_height"],0],"fill-extrusion-opacity":.72}},label)}catch(e){}
   const geo=neighborhoodGeo(selectedCity);map.addSource("neighborhoods",{type:"geojson",data:geo});map.addLayer({id:"neighborhood-fill",type:"fill",source:"neighborhoods",paint:{"fill-color":["get","color"],"fill-opacity":.25}});map.addLayer({id:"neighborhood-line",type:"line",source:"neighborhoods",paint:{"line-color":["get","color"],"line-width":2}});
   map.on("click","neighborhood-fill",e=>{const n=e.features[0].properties.name;document.querySelector(`[data-neigh="${CSS.escape(n)}"]`)?.click()});map.on("mouseenter","neighborhood-fill",()=>map.getCanvas().style.cursor="pointer");map.on("mouseleave","neighborhood-fill",()=>map.getCanvas().style.cursor="");
   CITIES[selectedCity].neighborhoods.forEach((n,i)=>{const m=document.createElement("button");m.className="chip on";m.textContent=n.name;m.style.borderColor=["#7652ff","#31d7ca","#e8b965","#38a1ff"][i%4];new maplibregl.Marker({element:m}).setLngLat([n.lon,n.lat]).setPopup(new maplibregl.Popup({offset:15}).setHTML(`<b>${n.name}</b><br>${n.desc}<br><strong>${n.score}% pour votre profil</strong>`)).addTo(map)});
   DEMO_HOTELS[selectedCity].slice(0,18).forEach((h,i)=>{const m=document.createElement("button");m.className="chip";m.textContent=(h.tier==="cheap"?"€":h.tier==="mid"?"€€":"€€€")+" "+h.price;m.style.background=h.tier==="cheap"?"#1e4938":h.tier==="premium"?"#463168":"#102b43";new maplibregl.Marker({element:m}).setLngLat([h.lon,h.lat]).setPopup(new maplibregl.Popup({offset:12}).setHTML(`<b>${h.name}</b><br>${h.neighborhood}<br>≈ ${h.price} € / nuit`)).addTo(map)});
 });
}
function bind(){
 document.querySelectorAll("[data-route]").forEach(x=>x.onclick=()=>route(x.dataset.route));document.querySelectorAll("[data-alfred]").forEach(x=>x.onclick=showAlfred);document.querySelectorAll("[data-toast]").forEach(x=>x.onclick=()=>showToast(x.dataset.toast));
 document.querySelectorAll("[data-city]").forEach(x=>x.onclick=()=>{selectedCity=x.dataset.city;localStorage.setItem("atlasCity",selectedCity);route("city")});
 document.querySelectorAll("[data-tab]").forEach(x=>x.onclick=()=>{activeTab=x.dataset.tab;render()});document.querySelectorAll("[data-tab-click]").forEach(x=>x.onclick=()=>{activeTab=x.dataset.tabClick;render()});
 document.querySelectorAll("[data-tier]").forEach(x=>x.onclick=()=>{hotelTier=x.dataset.tier;render()});document.querySelectorAll("[data-external]").forEach(x=>x.onclick=()=>window.open(x.dataset.external,"_blank","noopener"));
 document.querySelectorAll("[data-neigh]").forEach(x=>x.onclick=()=>{document.querySelectorAll(".neigh").forEach(n=>n.classList.remove("active"));x.classList.add("active");const n=CITIES[selectedCity].neighborhoods.find(n=>n.name===x.dataset.neigh);if(map&&n)map.flyTo({center:[n.lon,n.lat],zoom:14,pitch:55,duration:900})});
 const sel=document.getElementById("citySelect");if(sel)sel.onchange=()=>{selectedCity=sel.value;localStorage.setItem("atlasCity",selectedCity);render()};
 const p=document.querySelector("[data-parallax]");if(p){const h=p.parentElement;h.onpointermove=e=>{const r=h.getBoundingClientRect();p.style.transform=`scale(1.04) translate(${((e.clientX-r.left)/r.width-.5)*-10}px,${((e.clientY-r.top)/r.height-.5)*-7}px)`};h.onpointerleave=()=>p.style.transform="scale(1)"}
 
 document.querySelectorAll("[data-role]").forEach(x=>x.onclick=()=>{navigatorState.role=x.dataset.role;render()});
 document.querySelector("[data-reset-route]")?.addEventListener("click",()=>{navigatorState.stops=[{id:"s1",name:"Tirana",lat:41.3275,lng:19.8187,days:2}];syncRouteSource();showToast("Trajet réinitialisé à Tirana")});
 document.querySelector("[data-fit-route]")?.addEventListener("click",()=>{if(!routeMap||!navigatorState.stops.length)return;const b=new maplibregl.LngLatBounds();navigatorState.stops.forEach(s=>b.extend([s.lng,s.lat]));routeMap.fitBounds(b,{padding:80,duration:700})});
 document.querySelectorAll("[data-approve-proposal]").forEach(x=>x.onclick=()=>{const p=navigatorState.proposals.find(p=>p.id===x.dataset.approveProposal);if(p){navigatorState.stops.push({id:"s"+Date.now(),name:p.name,lat:p.lat,lng:p.lng,days:2});navigatorState.proposals=navigatorState.proposals.filter(q=>q.id!==p.id);render();showToast(`${p.name} approuvé et ajouté au trajet`)}});
 document.querySelectorAll("[data-reject-proposal]").forEach(x=>x.onclick=()=>{navigatorState.proposals=navigatorState.proposals.filter(p=>p.id!==x.dataset.rejectProposal);render();showToast("Proposition refusée")});
 document.querySelectorAll("[data-approve-request]").forEach(x=>x.onclick=()=>{const r=navigatorState.requests.find(r=>r.id===x.dataset.approveRequest);if(r){r.status="approved";navigatorState.members.push(r.name);navigatorState.messages.push({from:"Mondo",text:`${r.name} a rejoint le voyage.`});render();showToast(`${r.name} a rejoint le groupe`)}});
 document.querySelectorAll("[data-reject-request]").forEach(x=>x.onclick=()=>{const r=navigatorState.requests.find(r=>r.id===x.dataset.rejectRequest);if(r)r.status="rejected";render();showToast("Demande refusée")});
 document.querySelector("[data-request-join]")?.addEventListener("click",()=>{const t=document.getElementById("joinMessage")?.value.trim();if(!t){showToast("Ajoutez un petit message de présentation");return}navigatorState.requests.push({id:"r"+Date.now(),name:"Vous",initials:"VO",message:t,status:"pending"});render();showToast("Demande envoyée à l’organisateur")});
 document.querySelector("[data-send-message]")?.addEventListener("click",()=>{const inp=document.getElementById("chatInput"),t=inp?.value.trim();if(!t)return;navigatorState.messages.push({from:"Nassim",text:t});render()});

 const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("on")}),{threshold:.05});document.querySelectorAll(".reveal").forEach(x=>io.observe(x));
}
function render(){if(globe){try{globe._destructor&&globe._destructor()}catch(e){}globe=null}if(map){try{map.remove()}catch(e){}map=null}const pages={entry,mondo,atlas,explore,city,stays,flights,trip,navigator,mondoblog,community,atlasblog};app.innerHTML=(pages[current()]||entry)();bind();scrollTo(0,0);requestAnimationFrame(()=>{initGlobe();initMap();drawNavigator()})}
window.addEventListener("hashchange",render);render();
